-- Upstream: test/sql/types/floats.test
CREATE TABLE upstream_float_real (f real) USING ducklake;
INSERT INTO upstream_float_real VALUES (1), (10), ('NaN'), (1);
SELECT count(*) FROM upstream_float_real WHERE f = 'NaN';
SELECT count(*) FROM upstream_float_real WHERE f > 'NaN';
SELECT count(*) FROM upstream_float_real WHERE f >= 'NaN';
SELECT count(*) FROM upstream_float_real WHERE f < 'NaN';
SELECT count(*) FROM upstream_float_real WHERE f <= 'NaN';
SELECT count(*) FROM upstream_float_real WHERE f > 1;
INSERT INTO upstream_float_real VALUES ('Infinity'), ('-Infinity');
SELECT count(*) FROM upstream_float_real WHERE f > 'Infinity';
SELECT count(*) FROM upstream_float_real WHERE f >= 'Infinity';
SELECT count(*) FROM upstream_float_real WHERE f < 'Infinity';
SELECT count(*) FROM upstream_float_real WHERE f <= 'Infinity';
SELECT count(*) FROM upstream_float_real WHERE f > '-Infinity';
SELECT count(*) FROM upstream_float_real WHERE f >= '-Infinity';
CREATE TABLE upstream_float_double (f double precision) USING ducklake;
INSERT INTO upstream_float_double VALUES (1), (10), ('NaN'), (1);
SELECT count(*) FROM upstream_float_double WHERE f = 'NaN';
SELECT count(*) FROM upstream_float_double WHERE f > 'NaN';
SELECT count(*) FROM upstream_float_double WHERE f >= 'NaN';
SELECT count(*) FROM upstream_float_double WHERE f < 'NaN';
SELECT count(*) FROM upstream_float_double WHERE f <= 'NaN';
SELECT count(*) FROM upstream_float_double WHERE f > 1;
INSERT INTO upstream_float_double VALUES ('Infinity'), ('-Infinity');
SELECT count(*) FROM upstream_float_double WHERE f > 'Infinity';
SELECT count(*) FROM upstream_float_double WHERE f >= 'Infinity';
SELECT count(*) FROM upstream_float_double WHERE f < 'Infinity';
SELECT count(*) FROM upstream_float_double WHERE f <= 'Infinity';
SELECT count(*) FROM upstream_float_double WHERE f > '-Infinity';
SELECT count(*) FROM upstream_float_double WHERE f >= '-Infinity';
DROP TABLE upstream_float_real, upstream_float_double;
