-- Upstream: test/sql/rewrite_data_files/insert_delete_loop.test
-- Repeated insert/delete/rewrite cycles preserve the surviving rows.
CALL ducklake.set_option('data_inlining_row_limit', 0);
CALL ducklake.set_option('rewrite_delete_threshold', 0);
CREATE TABLE upstream_rewrite_loop (i integer) USING ducklake;
INSERT INTO upstream_rewrite_loop SELECT i FROM generate_series(1000, 1999) AS g(i);
DELETE FROM upstream_rewrite_loop WHERE i BETWEEN 1000 AND 1950;
SELECT * FROM ducklake.rewrite_data_files('upstream_rewrite_loop'::regclass);
INSERT INTO upstream_rewrite_loop SELECT i FROM generate_series(2000, 2999) AS g(i);
DELETE FROM upstream_rewrite_loop WHERE i BETWEEN 2000 AND 2950;
SELECT * FROM ducklake.rewrite_data_files('upstream_rewrite_loop'::regclass);
INSERT INTO upstream_rewrite_loop SELECT i FROM generate_series(3000, 3999) AS g(i);
DELETE FROM upstream_rewrite_loop WHERE i BETWEEN 3000 AND 3950;
SELECT count(*) = 147 AS count_before_rewrite FROM upstream_rewrite_loop;
SELECT * FROM ducklake.rewrite_data_files('upstream_rewrite_loop'::regclass);
SELECT count(*) = 147 AS count_after_rewrite FROM upstream_rewrite_loop;
INSERT INTO upstream_rewrite_loop SELECT i FROM generate_series(4000, 4999) AS g(i);
DELETE FROM upstream_rewrite_loop WHERE i BETWEEN 4000 AND 4950;
SELECT * FROM ducklake.rewrite_data_files('upstream_rewrite_loop'::regclass);
INSERT INTO upstream_rewrite_loop SELECT i FROM generate_series(5000, 5999) AS g(i);
DELETE FROM upstream_rewrite_loop WHERE i BETWEEN 5000 AND 5950;
SELECT * FROM ducklake.rewrite_data_files('upstream_rewrite_loop'::regclass);
INSERT INTO upstream_rewrite_loop SELECT i FROM generate_series(6000, 6999) AS g(i);
DELETE FROM upstream_rewrite_loop WHERE i BETWEEN 6000 AND 6950;
SELECT * FROM ducklake.rewrite_data_files('upstream_rewrite_loop'::regclass);
INSERT INTO upstream_rewrite_loop SELECT i FROM generate_series(7000, 7999) AS g(i);
DELETE FROM upstream_rewrite_loop WHERE i BETWEEN 7000 AND 7950;
SELECT * FROM ducklake.rewrite_data_files('upstream_rewrite_loop'::regclass);
INSERT INTO upstream_rewrite_loop SELECT i FROM generate_series(8000, 8999) AS g(i);
DELETE FROM upstream_rewrite_loop WHERE i BETWEEN 8000 AND 8950;
SELECT * FROM ducklake.rewrite_data_files('upstream_rewrite_loop'::regclass);
INSERT INTO upstream_rewrite_loop SELECT i FROM generate_series(9000, 9999) AS g(i);
DELETE FROM upstream_rewrite_loop WHERE i BETWEEN 9000 AND 9950;
SELECT * FROM ducklake.rewrite_data_files('upstream_rewrite_loop'::regclass);
INSERT INTO upstream_rewrite_loop SELECT i FROM generate_series(10000, 10999) AS g(i);
DELETE FROM upstream_rewrite_loop WHERE i BETWEEN 10000 AND 10950;
SELECT * FROM ducklake.rewrite_data_files('upstream_rewrite_loop'::regclass);
SELECT count(*), min(i), max(i) FROM upstream_rewrite_loop;
DROP TABLE upstream_rewrite_loop;
