-- Upstream: test/sql/alter/rename_table.test
CREATE TABLE upstream_rename_table (i integer) USING ducklake;
INSERT INTO upstream_rename_table VALUES (42);
ALTER TABLE upstream_rename_table RENAME TO upstream_rename_table2;
SELECT * FROM upstream_rename_table2 ORDER BY i;
BEGIN;
CREATE TABLE upstream_rename_local (i text) USING ducklake;
INSERT INTO upstream_rename_local VALUES ('42');
ALTER TABLE upstream_rename_local RENAME TO upstream_rename_local2;
INSERT INTO upstream_rename_local2 VALUES ('84');
ALTER TABLE upstream_rename_local2 RENAME TO upstream_rename_local3;
SELECT * FROM upstream_rename_local3 ORDER BY i;
COMMIT;
SELECT * FROM upstream_rename_local3 ORDER BY i;
BEGIN;
INSERT INTO upstream_rename_table2 VALUES (1);
ALTER TABLE upstream_rename_table2 RENAME TO upstream_rename_table3;
INSERT INTO upstream_rename_table3 VALUES (2);
ALTER TABLE upstream_rename_table3 RENAME TO upstream_rename_table4;
INSERT INTO upstream_rename_table4 VALUES (3);
ALTER TABLE upstream_rename_table4 RENAME TO upstream_rename_table5;
INSERT INTO upstream_rename_table5 VALUES (4);
COMMIT;
SELECT * FROM upstream_rename_table5 ORDER BY i;
SELECT to_regclass('upstream_rename_table2'), to_regclass('upstream_rename_table3'),
       to_regclass('upstream_rename_table4');
BEGIN;
ALTER TABLE upstream_rename_table5 RENAME TO upstream_rename_table6;
DROP TABLE upstream_rename_table6;
SELECT to_regclass('upstream_rename_table6') IS NULL AS renamed_table_dropped;
COMMIT;
ALTER TABLE upstream_nonexistent_table RENAME TO upstream_target;
SELECT to_regclass('upstream_target') IS NULL AS missing_source_not_renamed;
DROP TABLE upstream_rename_local3;
